version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.dashboard.address=:8080"
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"       # Mappe le port 80 de l'hôte au port 80 du conteneur
      - "8080:8080"   # Tableau de bord de Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge