version: "3.8"

services:
  whoami-on-port-80:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoint.dashboard.adress=:8080"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host('localhost')"
      - "traefik.http.services.app.loadbalancer.server.port=80"