version: "3"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - traefik_network

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.supersudoku.duckdns.org`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - traefik_network

  sudoku:
    environment:
      - JAVALIN_HOST=0.0.0.0
    build: .
    restart: unless-stopped
    networks:
      - traefik_network
    expose:
      - "1236"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sudoku-http.rule=Host(`supersudoku.duckdns.org`)"
      - "traefik.http.routers.sudoku-http.entrypoints=web"
      - "traefik.http.routers.sudoku.rule=Host(`supersudoku.duckdns.org`)"
      - "traefik.http.routers.sudoku.entrypoints=websecure"
      - "traefik.http.routers.sudoku.tls=true"
      - "traefik.http.routers.sudoku.tls.certresolver=myresolver"

volumes:
  letsencrypt:

networks:
  traefik_network: