version: '3'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.dashboard.address=:8081"
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - mynetwork

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge